vich_uploader:
    db_driver: orm

    mappings:
        societes:
            uri_prefix: /images/societes
            upload_destination: '%kernel.project_dir%/public/images/societes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
